<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE stories [
  <!ELEMENT stories (story+)>
  <!ELEMENT story (title, author, language, rating, genre, world, description, wwwLink, imageFile, mediaType)>
  <!ELEMENT title (#PCDATA)>
  <!ELEMENT author (#PCDATA)>
  <!ELEMENT language (#PCDATA)>
  <!ELEMENT rating (contentWarning)>
  <!ATTLIST rating ratingName (G | PG | M | M15 | MA | R | X) "G">
  <!ELEMENT contentWarning (#PCDATA)>
  <!ELEMENT genre (#PCDATA)>
  <!ELEMENT world (#PCDATA)>
  <!ELEMENT description (#PCDATA)>
  <!ELEMENT wwwLink (#PCDATA)>
  <!ELEMENT imageFile (#PCDATA)>
  <!ELEMENT mediaType (description)>
  <!ATTLIST mediaType type CDATA #REQUIRED>
  <!ATTLIST mediaType length CDATA #REQUIRED>
  <!ATTLIST mediaType lengthIn (pages | minutes) "minutes">
]>
<stories>
  <story>
    <title></title>
    <author></author>
    <language></language>
    <rating ratingName="G">
      <contentWarning></contentWarning>
    </rating>
    <genre></genre>
    <world></world>
    <description></description>
    <wwwLink></wwwLink>
    <imageFile></imageFile>
    <mediaType type="" length="0" lengthIn="minutes">
      <description></description>
    </mediaType>
  </story>
</stories>
